/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.1/userguide/building_java_projects.html in the Gradle documentation.
 */

 import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("de.vandermeer:asciitable:0.3.2")
    
    // Para envío de correo
    implementation("com.sun.mail:javax.mail:1.6.2")
    
    // Para JSON (persistencia)
    implementation("com.google.code.gson:gson:2.10.1")
    
    // Para manejo de fechas
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.0")
    
    // Para generación de PDF
    implementation("com.itextpdf:itext7-core:7.2.5")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

// Configurar la tarea shadowJar para empaquetar todas las dependencias
tasks.withType<ShadowJar> {
    manifest {
        attributes(
            "Main-Class" to "org.example.AppKt"  // Cambia esto a tu clase principal
        )
    }
}

// Asegurarte de que el JAR de sombra sea el artefacto predeterminado
tasks {
    build {
        dependsOn(shadowJar)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
