# Configuración de correo SMTP
# Para Gmail, necesitas crear una "Contraseña de aplicación"
# https://myaccount.google.com/apppasswords

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.usuario=tu_email@gmail.com
mail.password=tu_contraseña_de_aplicacion
mail.remitente=tu_email@gmail.com