/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AppTest {
    @Test 
    fun testCrearInventario() {
        val inventario = crearInventario()
        assertNotNull(inventario, "El inventario no debe ser nulo")
        assertTrue(inventario.isNotEmpty(), "El inventario debe tener productos")
    }
    
    @Test
    fun testCarritoVacio() {
        val carrito = Carrito()
        assertTrue(carrito.obtenerTotal() == 0.0, "El carrito vacío debe tener total 0")
    }
    
    @Test
    fun testAgregarProductoAlCarrito() {
        val carrito = Carrito()
        val producto = Producto(1, "Test", 10.0)
        carrito.agregarProducto(producto, 2)
        assertTrue(carrito.obtenerTotal() == 20.0, "El total debe ser 20.0")
    }
}
